from __future__ import annotations

import json
import locale
import re
import shutil
import subprocess
import sys
from collections.abc import Callable
from datetime import datetime
from pathlib import Path

from .discovery import (
    detect_parallel_node,
    find_fluent_root,
    find_ntbin_dir,
    find_release_dir,
    find_template_paths,
    find_vsdevcmd,
)
from .models import BuildSpec, BuildSummary, BuildTargetResult, ToolchainInfo


MANIFEST_NAME = ".pyfluent_lite_udf_build.json"
BuildEventCallback = Callable[[str, str | None, str], None]
CancelRequestedCallback = Callable[[], bool]


class BuildCancelledError(RuntimeError):
    """Raised when the caller cancels an in-flight build."""


def _ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def _emit(callback: BuildEventCallback | None, level: str, scope: str | None, message: str) -> None:
    if callback:
        callback(level, scope, message)


def _safe_remove_tree(path: Path, build_root: Path) -> None:
    if not path.exists():
        return
    resolved = path.resolve()
    root_resolved = build_root.resolve()
    try:
        resolved.relative_to(root_resolved)
    except ValueError as exc:
        raise ValueError(f"Refusing to delete path outside build root: {resolved}") from exc
    if resolved == root_resolved:
        raise ValueError(f"Refusing to delete the entire build root directly: {resolved}")
    shutil.rmtree(resolved)


def clean_build_root(build_root: Path, arch: str) -> list[Path]:
    removed: list[Path] = []
    if not build_root.exists():
        return removed

    for candidate in [build_root / "src", build_root / arch, build_root / "logs"]:
        if candidate.exists():
            _safe_remove_tree(candidate, build_root)
            removed.append(candidate)

    manifest_path = build_root / MANIFEST_NAME
    if manifest_path.exists():
        manifest_path.unlink()
        removed.append(manifest_path)

    return removed


def collect_input_files(spec: BuildSpec) -> tuple[list[Path], list[Path]]:
    c_files = [path.resolve() for path in spec.c_files]
    header_files = [path.resolve() for path in spec.header_files]

    if c_files or header_files:
        for path in c_files + header_files:
            if not path.is_file():
                raise FileNotFoundError(f"Input file does not exist: {path}")
    else:
        if not spec.source_dir.is_dir():
            raise FileNotFoundError(f"Source directory does not exist: {spec.source_dir}")
        iterator = spec.source_dir.rglob("*") if spec.recursive else spec.source_dir.glob("*")
        for path in iterator:
            if not path.is_file():
                continue
            if spec.build_root.resolve() in path.resolve().parents:
                continue
            suffix = path.suffix.lower()
            if suffix == ".c":
                c_files.append(path.resolve())
            elif suffix in {".h", ".hpp"}:
                header_files.append(path.resolve())

    if not c_files:
        raise ValueError(f"No .c files found in {spec.source_dir}.")

    duplicates: dict[str, list[Path]] = {}
    for path in c_files + header_files:
        duplicates.setdefault(path.name.lower(), []).append(path)
    collisions = {name: paths for name, paths in duplicates.items() if len(paths) > 1}
    if collisions:
        lines = [
            f"{name}: {', '.join(str(path) for path in paths)}"
            for name, paths in sorted(collisions.items())
        ]
        raise ValueError(
            "Duplicate basenames are not supported because the official libudf layout uses a flat src directory:\n"
            + "\n".join(lines)
        )

    return sorted(c_files), sorted(header_files)


def _copy_files(files: list[Path], destination: Path) -> None:
    for source in files:
        shutil.copy2(source, destination / source.name)


def _source_ref(path: Path) -> str:
    if " " in path.name:
        return f'$(SRC)"{path.name}"'
    return f"$(SRC){path.name}"


def render_user_udf(version: str, c_files: list[Path], parallel_node: str) -> str:
    c_sources = " ".join(_source_ref(path) for path in c_files)
    # Keep HSOURCES empty. Headers are copied for #include resolution without
    # being treated as pseudo-sources by Fluent's stock Windows makefile.
    return "\n".join(
        [
            "###########################################################",
            "## Generated by PyFluent Lite",
            "## This file is rewritten on every local UDF build.",
            "###########################################################",
            "",
            f"CSOURCES = {c_sources}",
            "HSOURCES =",
            f"VERSION = {version}",
            f"PARALLEL_NODE = {parallel_node}",
            "",
            "USER_OBJECTS =",
            "",
        ]
    )


def _version_for_target(solver: str, target: str) -> tuple[str, str]:
    if target == "serial":
        return solver, "none"
    if target == "host":
        return f"{solver}_host", "none"
    if target == "node":
        return f"{solver}_node", "auto"
    raise ValueError(f"Unsupported target: {target}")


def _extract_lines(log_text: str, pattern: re.Pattern[str], limit: int = 20) -> list[str]:
    matches: list[str] = []
    for line in log_text.splitlines():
        if pattern.search(line):
            matches.append(line.rstrip())
            if len(matches) >= limit:
                break
    return matches


def _classify_output_line(
    line: str,
    error_pattern: re.Pattern[str],
    warning_pattern: re.Pattern[str],
) -> str:
    if error_pattern.search(line):
        return "error"
    if warning_pattern.search(line):
        return "warning"
    return "info"


def _build_command(toolchain: ToolchainInfo, arch: str, target: str, parallel_node: str) -> str:
    return (
        f'call "{toolchain.vsdevcmd}" -arch=x64 -host_arch=x64 >nul'
        f' && set "FLUENT_INC={toolchain.fluent_root}"'
        f' && set "FLUENT_ARCH={arch}"'
        f' && set "UDF_PARALLEL_NODE={parallel_node}"'
        f' && set "PATH={toolchain.ntbin_dir};%PATH%"'
        " && nmake"
    )


def _write_command_script(
    script_path: Path,
    toolchain: ToolchainInfo,
    arch: str,
    parallel_node: str,
) -> None:
    lines = [
        "@echo off",
        f'call "{toolchain.vsdevcmd}" -arch=x64 -host_arch=x64 >nul',
        "if errorlevel 1 exit /b %errorlevel%",
        f'set "FLUENT_INC={toolchain.fluent_root}"',
        f'set "FLUENT_ARCH={arch}"',
        f'set "UDF_PARALLEL_NODE={parallel_node}"',
        f'set "PATH={toolchain.ntbin_dir};%PATH%"',
        "nmake",
        "exit /b %errorlevel%",
        "",
    ]
    script_path.write_text("\n".join(lines), encoding="utf-8")


def _prepare_target_tree(
    build_root: Path,
    arch: str,
    target: str,
    makefile_template: Path,
    user_text: str,
) -> tuple[Path, Path]:
    version_dir = build_root / arch / target
    _ensure_dir(version_dir)
    makefile_path = version_dir / "makefile"
    user_udf_path = version_dir / "user_nt.udf"
    shutil.copy2(makefile_template, makefile_path)
    user_udf_path.write_text(user_text, encoding="utf-8")
    return version_dir, user_udf_path


def discover_toolchain(spec: BuildSpec) -> ToolchainInfo:
    fluent_root = find_fluent_root(str(spec.fluent_root) if spec.fluent_root else None)
    release_dir = find_release_dir(fluent_root, str(spec.release_dir) if spec.release_dir else None)
    makefile_template, user_template = find_template_paths(release_dir)
    ntbin_dir = find_ntbin_dir(fluent_root, spec.arch)
    vsdevcmd = find_vsdevcmd(str(spec.vsdevcmd) if spec.vsdevcmd else None)
    node_parallel_mode = detect_parallel_node(release_dir, spec.arch, spec.solver, spec.parallel_node)
    return ToolchainInfo(
        fluent_root=fluent_root,
        release_dir=release_dir,
        makefile_template=makefile_template,
        user_template=user_template,
        ntbin_dir=ntbin_dir,
        vsdevcmd=vsdevcmd,
        node_parallel_mode=node_parallel_mode,
    )


def _write_manifest(
    spec: BuildSpec,
    toolchain: ToolchainInfo,
    c_files: list[Path],
    header_files: list[Path],
) -> Path:
    manifest_path = spec.build_root / MANIFEST_NAME
    payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "project_dir": str(spec.project_dir),
        "build_root": str(spec.build_root),
        "source_dir": str(spec.source_dir),
        "solver": spec.solver,
        "targets": list(spec.targets),
        "parallel_node": toolchain.node_parallel_mode,
        "arch": spec.arch,
        "c_files": [str(path) for path in c_files],
        "header_files": [str(path) for path in header_files],
        "fluent_root": str(toolchain.fluent_root),
        "release_dir": str(toolchain.release_dir),
        "vsdevcmd": str(toolchain.vsdevcmd),
        "python": sys.executable,
    }
    manifest_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest_path


def build(spec: BuildSpec) -> BuildSummary:
    return build_with_callback(spec)


def build_with_callback(
    spec: BuildSpec,
    event_callback: BuildEventCallback | None = None,
    cancel_requested: CancelRequestedCallback | None = None,
) -> BuildSummary:
    def is_cancelled() -> bool:
        return bool(cancel_requested and cancel_requested())

    spec.validate()
    if is_cancelled():
        raise BuildCancelledError("Build cancelled before start.")

    _emit(event_callback, "status", None, "Collecting source files")
    c_files, header_files = collect_input_files(spec)
    _emit(event_callback, "info", None, f"Found {len(c_files)} C files and {len(header_files)} header files")

    _emit(event_callback, "status", None, "Discovering Fluent and Visual Studio toolchains")
    toolchain = discover_toolchain(spec)
    _emit(event_callback, "success", None, f"Fluent release: {toolchain.release_dir}")
    _emit(event_callback, "success", None, f"VsDevCmd: {toolchain.vsdevcmd}")
    _emit(event_callback, "success", None, f"PARALLEL_NODE: {toolchain.node_parallel_mode}")

    if spec.dry_run:
        target_results: list[BuildTargetResult] = []
        for target in spec.targets:
            if is_cancelled():
                raise BuildCancelledError("Build cancelled during dry-run.")
            version, parallel_node = _version_for_target(spec.solver, target)
            if parallel_node == "auto":
                parallel_node = toolchain.node_parallel_mode
            target_dir = spec.build_root / spec.arch / version
            command = _build_command(toolchain, spec.arch, version, parallel_node)
            _emit(event_callback, "command", target, command)
            target_results.append(
                BuildTargetResult(
                    target=target,
                    version=version,
                    target_dir=target_dir,
                    user_udf_path=target_dir / "user_nt.udf",
                    log_path=spec.build_root / "logs" / f"{version}.log",
                    command=command,
                    returncode=None,
                    success=False,
                )
            )

        return BuildSummary(
            ok=True,
            spec=spec,
            toolchain=toolchain,
            source_files=c_files,
            header_files=header_files,
            manifest_path=None,
            target_results=target_results,
        )

    _ensure_dir(spec.build_root)
    if spec.fresh:
        if is_cancelled():
            raise BuildCancelledError("Build cancelled before cleanup.")
        _emit(event_callback, "status", None, f"Cleaning build root: {spec.build_root}")
        clean_build_root(spec.build_root, spec.arch)

    src_dir = _ensure_dir(spec.build_root / "src")
    logs_dir = _ensure_dir(spec.build_root / "logs")
    if is_cancelled():
        raise BuildCancelledError("Build cancelled before staging sources.")
    _emit(event_callback, "status", None, f"Copying inputs to {src_dir}")
    _copy_files(c_files, src_dir)
    _copy_files(header_files, src_dir)

    manifest_path = _write_manifest(spec, toolchain, c_files, header_files)
    _emit(event_callback, "info", None, f"Manifest written: {manifest_path}")
    target_results: list[BuildTargetResult] = []

    encoding = locale.getpreferredencoding(False) or "utf-8"
    error_pattern = re.compile(r"\b(fatal error|error [A-Z]?\d+|U\d{4}: error)\b", re.IGNORECASE)
    warning_pattern = re.compile(r"\bwarning\b", re.IGNORECASE)

    for target in spec.targets:
        if is_cancelled():
            raise BuildCancelledError("Build cancelled before target execution.")
        version, parallel_node = _version_for_target(spec.solver, target)
        if parallel_node == "auto":
            parallel_node = toolchain.node_parallel_mode

        target_dir, user_udf_path = _prepare_target_tree(
            build_root=spec.build_root,
            arch=spec.arch,
            target=version,
            makefile_template=toolchain.makefile_template,
            user_text=render_user_udf(version=version, c_files=c_files, parallel_node=parallel_node),
        )

        log_path = logs_dir / f"{version}.log"
        command = _build_command(toolchain, spec.arch, version, parallel_node)
        command_script = logs_dir / f"{version}.cmd"
        _write_command_script(command_script, toolchain, spec.arch, parallel_node)
        _emit(event_callback, "status", target, f"Starting {version}")
        _emit(event_callback, "command", target, command)

        log_chunks: list[str] = []
        try:
            process = subprocess.Popen(
                ["cmd.exe", "/d", "/c", str(command_script)],
                cwd=target_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                encoding=encoding,
                errors="replace",
                bufsize=1,
            )
        except OSError as exc:
            raise RuntimeError(
                f"Failed to start build process for {version}: {exc}. "
                f"Command script: {command_script}"
            ) from exc
        assert process.stdout is not None
        for raw_line in process.stdout:
            if is_cancelled():
                _emit(event_callback, "warning", target, f"Cancelling {version} ...")
                process.terminate()
                try:
                    process.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    process.kill()
                process.stdout.close()
                raise BuildCancelledError(f"Build cancelled during {version}.")
            log_chunks.append(raw_line)
            line = raw_line.rstrip("\r\n")
            if line:
                _emit(event_callback, _classify_output_line(line, error_pattern, warning_pattern), target, line)
        process.stdout.close()
        returncode = process.wait()
        log_text = "".join(log_chunks)
        log_path.write_text(log_text, encoding="utf-8")

        dll_path = target_dir / "libudf.dll"
        success = returncode == 0 and dll_path.is_file()
        if success:
            _emit(event_callback, "success", target, f"{version} build succeeded")
            _emit(event_callback, "success", target, f"DLL: {dll_path}")
        else:
            _emit(event_callback, "error", target, f"{version} build failed")
            _emit(event_callback, "error", target, f"See log: {log_path}")

        target_results.append(
            BuildTargetResult(
                target=target,
                version=version,
                target_dir=target_dir,
                user_udf_path=user_udf_path,
                log_path=log_path,
                command=command,
                returncode=returncode,
                success=success,
                dll_path=dll_path if dll_path.is_file() else None,
                error_lines=_extract_lines(log_text, error_pattern),
                warning_lines=_extract_lines(log_text, warning_pattern),
            )
        )

    ok = all(result.success for result in target_results)
    _emit(
        event_callback,
        "success" if ok else "error",
        None,
        "Build finished" if ok else "Build finished with failures",
    )
    return BuildSummary(
        ok=ok,
        spec=spec,
        toolchain=toolchain,
        source_files=c_files,
        header_files=header_files,
        manifest_path=manifest_path,
        target_results=target_results,
    )
